SPRINGER_API_KEY = "c6fbe20e8c1102e00c28a61e88aa07f1"
ELSEVIER_API_KEY = "3491ff60052c9d5ac2b6f0f2cdc52c7d"
IEEE_API_KEY = "n59ht6fz932x3jrbwzkzezfb"
CROSSREF_EMAIL = "mohamed.aneddame-ext@um6p.ma"
SEMANTIC_SCHOLAR_API_KEY = "npGsrLciX44qBf9vQ0TTV53XEGjN4hrRHlQ0VKhf"
EMAIL = "mohamed.aneddame-ext@um6p.ma"
